steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Configure git
  entrypoint: /bin/bash
  args:
  - '-c'
  - |
    git config --global init.defaultBranch main && \
    git config --global user.email "rohitmishra@google.com" && \
    git clone https://github.com/rmishgoog/kustomize-kubernetes-manifests

- name: 'gcr.io/cloud-builders/gcloud'
  id: Update manifest
  entrypoint: /bin/bash
  args:
  - '-c'
  - |
     cd kustomize-kubernetes-manifests && \
     sed "s/PROJECT_ID/${PROJECT_ID}/g" overlays/production/template/product-listing-api-prod-patch.tpl.yaml | \
     sed "s/SHORT_SHA/$_SHORT_SHA/g" > overlays/production/manifests/product-listing-api-prod-patch.yaml

- name: 'gcr.io/cloud-builders/gcloud'
  id: Push manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    cd kustomize-kubernetes-manifests && \
    set -x && \
    git config --global init.defaultBranch main && \
    git config --global user.email "rohitmishra@google.com" && \
    git add overlays/production/manifests/product-listing-api-prod-patch.yaml && \
    git commit -m "Deploying the image with tag ${_SHORT_SHA}" && \
    git push https://$$_GITHUB_TOKEN@github.com/rmishgoog/kustomize-kubernetes-manifests
  secretEnv: ['_GITHUB_TOKEN']

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/github-commits-cloud-build/versions/latest
      env: '_GITHUB_TOKEN'