steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: Generate manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
     sed "s/PROJECT_ID/${PROJECT_ID}/g" overlays/development/product-listing-api/product-listing-api-dev-patch.yaml | \
     sed "s/SHORT_SHA/${_IMAGE_TAG}/g" > overlays/development/product-listing-api/product-listing-api-dev-patch.yaml

- name: 'gcr.io/cloud-builders/gcloud'
  id: Push manifest
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    set -x && \
    git config --global user.email "rohitmishra@google.com" && \
    git add overlays/development/product-listing-api/product-listing-api-dev-patch.yaml && \
    git commit -m "Deploying gcr.io/$PROJECT_ID/product-listing-api:${_IMAGE_TAG}" && \
    git push origin main