apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-listing-api
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%    
  replicas: 2
  selector:
    matchLabels:
      app: product-listing-api
  template:
    metadata:
      labels:
        app: product-listing-api
    spec:
      containers:
        - name: product-listing-api
          image: gcr.io/rmishra-gke-cicd-demo-build/product-listing-api@sha256:48a7d740142353063c79c244a1325653893df9faf9902f5de5f80d5cf6dc02f6
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "300m"
              memory: "512Mi"

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: product-listing-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-listing-api
  minReplicas: 2
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70

---
apiVersion: v1
kind: Secret
metadata:
  name: prod-listing-api-db-crednetials
type: Opaque
data:
  prod-listing-api-db-usr: cHJvZF9wcmRfZGV0YWlsc19wb3N0Z3Jlc191c3IK
  prod-listing-api-db-pwd: SEFSRElLUGFuZHlhQDc4Ngo=