apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-listing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-listing-api
  template:
    metadata:
      labels:
        app: product-listing-api
    spec:
      containers:
        - name: product-listing-api
          image: gcr.io/rmishra-gke-cicd-demo-build/product-listing-api@sha256:48a7d740142353063c79c244a1325653893df9faf9902f5de5f80d5cf6dc02f6
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "150m"
              memory: "256Mi"

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: product-listing-api-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: product-listing-api
  minReplicas: 1
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90

---
apiVersion: v1
kind: Secret
metadata:
  name: prod-listing-api-db-crednetials
type: Opaque
data:
  prod-listing-api-db-usr: ZGV2X3ByZF9kZXRhaWxzX3Bvc3RncmVzX3Vzcgo=
  prod-listing-api-db-pwd: RmFzdEBwcGxlNTQK