apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: catalog
resources:
  - product-listing-api.yaml
patchesStrategicMerge:
  - product-listing-api-base-patch.yaml
configMapGenerator:
- name: application-configs
  files:
  - application.properties
generatorOptions:
 disableNameSuffixHash: true